In [2]:
import MetaTrader5 as mt5

In [4]:
mt5.initialize()

True

In [14]:
from datetime import datetime
import MetaTrader5 as mt5
import pandas as pd
import pytz
 
# establish connection to MetaTrader 5 terminal
if not mt5.initialize():
    print("initialize() failed, error code =",mt5.last_error())
    quit()
 
# set time zone to UTC
timezone = pytz.timezone("Etc/UTC")
# create 'datetime' objects in UTC time zone to avoid the implementation of a local time zone offset
utc_from = datetime(2025, 3, 26, tzinfo=timezone)
utc_to = datetime(2025, 3, 29, tzinfo=timezone)
# get bars from USDJPY M5 within the interval of 2020.01.10 00:00 - 2020.01.11 13:00 in UTC time zone
rates = mt5.copy_rates_range("EURUSD", mt5.TIMEFRAME_M1, utc_from, utc_to)

# create DataFrame out of the obtained data
rates_frame = pd.DataFrame(rates)
# convert time in seconds into the 'datetime' format
rates_frame['time']=pd.to_datetime(rates_frame['time'], unit='s')
 
# display data
print("\nDisplay dataframe with data")
print(rates_frame.head(10))

Display dataframe with data
                 time     open     high      low    close  tick_volume  \
0 2025-03-26 00:00:00  1.07914  1.07927  1.07900  1.07908           43
1 2025-03-26 00:01:00  1.07908  1.07911  1.07907  1.07907           18
2 2025-03-26 00:02:00  1.07906  1.07910  1.07904  1.07907           11
3 2025-03-26 00:03:00  1.07907  1.07908  1.07905  1.07907           18
4 2025-03-26 00:04:00  1.07908  1.07910  1.07906  1.07906           17
5 2025-03-26 00:05:00  1.07907  1.07908  1.07906  1.07908            7
6 2025-03-26 00:06:00  1.07908  1.07916  1.07908  1.07911           13
7 2025-03-26 00:07:00  1.07923  1.07926  1.07911  1.07923           24
8 2025-03-26 00:08:00  1.07923  1.07928  1.07917  1.07920           14
9 2025-03-26 00:09:00  1.07923  1.07926  1.07911  1.07915           23

   spread  real_volume
0       8            0
1      12            0
2      12            0
3      16            0
4      17            0
5      14            0
6      11            0
7       8            0
8       8            0
9      12            0

In [15]:
rates_frame

,time,open,high,low,close,tick_volume,spread,real_volume
0,2025-03-26 00:00:00,1.07914,1.07927,1.07900,1.07908,43,8,0
1,2025-03-26 00:01:00,1.07908,1.07911,1.07907,1.07907,18,12,0
2,2025-03-26 00:02:00,1.07906,1.07910,1.07904,1.07907,11,12,0
3,2025-03-26 00:03:00,1.07907,1.07908,1.07905,1.07907,18,16,0
4,2025-03-26 00:04:00,1.07908,1.07910,1.07906,1.07906,17,17,0
...,...,...,...,...,...,...,...,...
4131,2025-03-28 20:51:00,1.08272,1.08273,1.08244,1.08245,42,9,0
4132,2025-03-28 20:52:00,1.08245,1.08248,1.08237,1.08241,49,12,0
4133,2025-03-28 20:53:00,1.08241,1.08241,1.08233,1.08234,24,8,0
4134,2025-03-28 20:54:00,1.08236,1.08242,1.08231,1.08240,43,8,0
4135,2025-03-28 20:55:00,1.08241,1.08242,1.08232,1.08237,23,10,0

In [ ]:
from sklearn.linear_model import LinearRegression
import numpy as np


model = LinearRegression()